function(metaref_add_example name)
    add_executable(example_${name} ${name}.cpp)
    target_link_libraries(example_${name} PRIVATE metaref::metaref)
    if(METAREF_BUILD_TESTS)
        add_test(NAME example_${name} COMMAND example_${name})
    endif()
endfunction()

metaref_add_example(debug_print)
metaref_add_example(hash)